# Generated by Django 5.1.2 on 2024-10-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.location'),
            preserve_default=False,
        ),
    ]
