# Generated by Django 5.1.2 on 2024-10-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_things_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thingsreadings',
            old_name='freading_till',
            new_name='reading_till',
        ),
    ]
