# Generated by Django 5.1.2 on 2024-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_rename_freading_till_thingsreadings_reading_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingsreadings',
            name='reading_till',
            field=models.DateTimeField(),
        ),
    ]
