# Generated by Django 5.1.2 on 2025-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_alter_thingsreadings_reading_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingsreadings',
            name='soil_humidity_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thingsreadings',
            name='soil_temp_reading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
