# Generated by Django 5.1.2 on 2025-04-27 15:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_thingsreadings_soil_humidity_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='panjayath',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='panjayath',
        ),
        migrations.RemoveField(
            model_name='things',
            name='panjayath',
        ),
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority_type', models.CharField(choices=[('municipal_corporation', 'Municipal Corporation'), ('municipality', 'Municipality'), ('gram_panchayat', 'Gram Panchayath')], max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.districts')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.states')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='localauthority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.localauthority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='things',
            name='localauthority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.localauthority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='localauthority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.localauthority'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Panjayath',
        ),
    ]
