# Generated by Django 5.1.2 on 2025-05-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_remove_location_panjayath_remove_ward_panjayath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='localauthority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.localauthority'),
        ),
        migrations.AlterField(
            model_name='things',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.location'),
        ),
        migrations.AlterField(
            model_name='things',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.ward'),
        ),
    ]
