# Generated by Django 5.1.2 on 2025-07-15 04:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_rename_temp_reading_thingsreadings_temp_reading_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='localauthority',
        ),
        migrations.RemoveField(
            model_name='things',
            name='localauthority',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='localauthority',
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='things',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='state',
        ),
        migrations.RemoveField(
            model_name='things',
            name='ward',
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.districts')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.states')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='things',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.cluster'),
        ),
        migrations.DeleteModel(
            name='LocalAuthority',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
